name: Push Stage version to DockerHub
on:
  push:
    branches:
      - 'dev'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cut commit sha
        id: cut
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Логинимся в репозитории Docker
      # https://github.com/docker/login-action
      - name: Log into DockerHUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCHUB_USERNAME }}
          password: ${{ secrets.DOCHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ vars.DOCHUB_USERNAME }}/var_keeper:${{ steps.cut.outputs.sha_short }}
